@startjson Structure de données
{
    "2017": [
        {
            "id_mutation": "...",
            "date_mutation": "...",
            "numero_disposition": "...",
            "nature_mutation": "...",
            "valeur_fonciere": "...",
            "adresse_numero": "...",
            "adresse_suffixe": "...",
            "adresse_code_voie": "...",
            "adresse_nom_voie": "...",
            "code_postal": "...",
            "code_commune": "...",
            "nom_commune": "...",
            "ancien_code_commune": "...",
            "ancien_nom_commune": "...",
            "code_departement": "...",
            "id_parcelle": "...",
            "ancien_id_parcelle": "...",
            "numero_volume": "...",
            "lot_1_numero": "...",
            "lot_1_surface_carrez": "...",
            "lot_2_numero": "...",
            "lot_2_surface_carrez": "...",
            "lot_3_numero": "...",
            "lot_3_surface_carrez": "...",
            "lot_4_numero": "...",
            "lot_4_surface_carrez": "...",
            "lot_5_numero": "...",
            "lot_5_surface_carrez": "...",
            "nombre_lots": "...",
            "code_type_local": "...",
            "type_local": "...",
            "surface_reelle_bati": "...",
            "nombre_pieces_principales": "...",
            "code_nature_culture": "...",
            "nature_culture": "...",
            "code_nature_culture_speciale": "...",
            "nature_culture_speciale": "...",
            "surface_terrain": "...",
            "longitude": "...",
            "latitude": "..."
        },
        {}
    ],
    "2018": "..."
}
@endjson
